# Generated by Django 4.2.9 on 2024-02-18 13:27

import blog.models
import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=700)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('prep_time', models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(300)], verbose_name='prep_time')),
                ('cooking_time', models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(600)], verbose_name='cooking_time')),
                ('servings', models.PositiveIntegerField(validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(50)], verbose_name='servings')),
                ('cuisines_type', models.CharField(choices=[('american', 'American'), ('african', 'African'), ('asian', 'Asian'), ('caribbean', 'Caribbean'), ('chinese', 'Chinese'), ('european', 'European'), ('indian', 'Indian'), ('indonesian', 'Indonesian'), ('latin_american', 'Latin American'), ('middle_eastern', 'Middle Eastern'), ('mexican', 'Mexican'), ('oceanic', 'Oceanic')], default='Asian', max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='recipe_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.recipe')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
