# Generated by Django 4.2.9 on 2024-02-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipe_servings_recipe_total_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine_types',
            field=models.CharField(choices=[('american', 'American'), ('african', 'African'), ('asian', 'Asian'), ('caribbean', 'Caribbean'), ('chinese', 'Chinese'), ('european', 'European'), ('indian', 'Indian'), ('indonesian', 'Indonesian'), ('latin_american', 'Latin American'), ('middle_eastern', 'Middle Eastern'), ('oceanic', 'Oceanic'), ('pakistani', 'Pakistani')], default='Asian', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save as Draft'), (1, 'Make it Public')], default=0),
        ),
    ]
