# Generated by Django 4.2.9 on 2024-02-12 09:00

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(600)], verbose_name='cooking_time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=1, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(300)], verbose_name='prep_time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(50)], verbose_name='servings'),
        ),
    ]
