# Generated by Django 4.2.9 on 2024-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_recipe_total_cooking_time_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine_types',
        ),
        migrations.AddField(
            model_name='recipe',
            name='world_cuisines',
            field=models.CharField(choices=[('american', 'American'), ('african', 'African'), ('asian', 'Asian'), ('caribbean', 'Caribbean'), ('chinese', 'Chinese'), ('european', 'European'), ('indian', 'Indian'), ('indonesian', 'Indonesian'), ('latin_american', 'Latin American'), ('middle_eastern', 'Middle Eastern'), ('mexican', 'Mexican'), ('oceanic', 'Oceanic')], default='Asian', max_length=60),
        ),
    ]
