# Generated by Django 4.2.9 on 2024-02-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_recipe_cuisine_types_recipe_world_cuisines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='world_cuisines',
            new_name='cuisines_type',
        ),
    ]
