# Generated by Django 4.2.9 on 2024-02-15 21:55

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_world_cuisines_recipe_cuisines_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(600)], verbose_name='cooking_time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(300)], verbose_name='prep_time'),
        ),
    ]
